drop table if exists reserva cascade;
drop table if exists guia cascade;
drop table if exists pasaporte cascade;
drop table if exists usuario cascade;
drop table if exists destino cascade;

create table pasaporte (
    fecha_caducidad date,
    id integer generated by default as identity,
    id_usuario integer unique,
    numero varchar(255),
    pais_expedicion varchar(255),
    primary key (id)
);

create table usuario (
    id integer generated by default as identity,
    nombre varchar(255),
    apellidos varchar(255),
    email varchar(255),
    telefono varchar(255),
    fecha_nacimiento date,
    primary key (id)
);

create table destino (
    id integer generated by default as identity,
    ciudad varchar(255),
    pais varchar(255),
    precio numeric(10,2),
    requiere_pasaporte boolean,
    primary key (id)
);

create table guia (
    id integer generated by default as identity,
    nombre varchar(255),
    apellidos varchar(255),
    especialidad varchar(255),
    id_destino integer,
    primary key (id),
    foreign key (id_destino) references destino(id)
);

create table reserva (
    id integer generated by default as identity,
    id_usuario integer,
    id_destino integer,
    primary key (id),
    foreign key (id_usuario) references usuario(id),
    foreign key (id_destino) references destino(id)
);

